### ISSUE TITLE
Ledders' navigation

### ISSUE THREAD

**Issue by kosyachniy** [tensegrity-dapp/blend#2]
- [x] Найти JS инструмент для построения многоуровневой круговой диаграммы
- [x] Переделать базу данных
- [x] Хранение / получение категорий для отображения диаграммы
- [x] Реализовать развёртывание вокруг нового центра
- [x] Присвоить каждому ледеру категорию
- [x] Реализовать добавление новых ледеров
- [x] Добавление категорий
- [x] Составить список категорий

### Idea
Реализовать круговую диаграмму для разбиения ледеров по принадлежности к области знаний (теоретическое разбиение)

### Description
При нажатии на определённую область - диаграмма раскрывается вокруг нового центра
Углубление идёт по: категории наук - наука - поднаука - раздел - тема - задача

### For what
1. Систематизация
2. Визуализация

### Required for Implementation
Добавить:
1. Принадлежность категории для каждого ледера
2. Добавление новых категорий

Решить:
1. Как добавлять новые ледеры
Будет ли возможность прямо при добавлении создать подраздел,
Нужно ли отдельно возможность создавать категории?

### Resources
[Решения](https://postovoy.net/javascript-biblioteki-dlya-sozdaniya-krugovyh-diagramm.html)
[Cake Chart JS](https://github.com/alexkuz/cake-chart)
!!! [Многоуровневая круговая диаграмма](https://www.fusioncharts.com/dev/chart-guide/standard-charts/multi-level-pie-chart)

**Comment by w0ckeezz** [comment]
Можно не круговую диаграмму а просто дерево

**Comment by w0ckeezz** [comment]
https://www.w3schools.com/howto/howto_js_treeview.asp - вариант без визуализации

**Comment by w0ckeezz** [comment]
https://github.com/jaredly/treed дерево слева направо
